# Shopping Application

In [4]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
f = open('demo.txt', 'r')
ds = eval(f.read())
f.close()
te=TransactionEncoder()
te=te.fit(ds)
te_ary=te.transform(ds)
df=pd.DataFrame(te_ary,columns=te.columns_)
all_items=te.columns_
ref=list(te.columns_)
cart=[]
display(df)
frequent_itemsets=apriori(df,min_support=0.01,use_colnames=True)
rules=association_rules(frequent_itemsets,metric="support",min_threshold=0.1)
display(rules)
print("**** Krithik's Bazaar ***** \nHere is what we sell")
print(te.columns_)
k=1
while len(all_items)!=0:
    buy=input("Do you want to Buy something?\nPress 'y' for Yes and 'n' for No: ")
    if (buy=='y') or (buy=='Y'):
        item=input("enter your item here: ")
        if (item in all_items):
            cart.append(item)
            all_items.remove(item)
            print(item,"is added to the cart\n",cart)
            newrules=rules[rules["antecedents"].apply(lambda x: set(cart).issubset(set(x)))]
            display(newrules)
            ml=list(newrules["consequents"])
            if len(ml)!=0:
                print("Do you want to Buy?")
                p=[list(i) for i in ml]
                for k in range(len(p)):
                    print(p[k])
        else:
            if(item in ref):
                print("Another",item,"is added to cart")
            else:
                print("We dont have that item in our bazaar,enter any of the following items",te.columns_)
    elif (buy=='n') or (buy=='N'):
        break
    else:
        print("Press only 'y' for yes or 'n' for no")
ds.append(cart)
if len(cart)!=0:
    fo=open('demo.txt','w')
    fo.write(repr(ds))
    fo.close()
    print("Your purchases are:",cart)
else:
    print("I am sorry,i couldnt Help you")

     Beer  Bread   Cola  Diapers   Eggs   Milk
0    True   True  False    False  False   True
1   False   True  False     True   True  False
2    True  False   True     True  False   True
3    True   True  False     True  False   True
4   False   True   True    False  False   True
5    True  False   True    False  False   True
6   False  False   True     True  False   True
7    True  False  False    False  False   True
8    True  False  False     True  False  False
9    True  False   True    False   True  False
10   True  False   True    False  False   True
11  False   True   True    False  False  False
12  False   True  False     True   True   True
13  False  False   True    False  False   True
14  False  False   True    False  False   True
15   True  False  False    False  False  False
16  False  False   True     True  False   True
17   True  False  False    False  False   True
18  False  False   True    False  False  False
19   True  False   True    False   True  False
20   True  False   True    False  False  False
21  False   True  False     True  False  False

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Cola),(Beer),0.590909,0.545455,0.272727,0.461538,0.846154,-0.049587,0.844156
1,(Beer),(Cola),0.545455,0.590909,0.272727,0.500000,0.846154,-0.049587,0.818182
2,(Diapers),(Beer),0.363636,0.545455,0.136364,0.375000,0.687500,-0.061983,0.727273
3,(Beer),(Diapers),0.545455,0.363636,0.136364,0.250000,0.687500,-0.061983,0.848485
4,(Milk),(Beer),0.590909,0.545455,0.318182,0.538462,0.987179,-0.004132,0.984848
5,(Beer),(Milk),0.545455,0.590909,0.318182,0.583333,0.987179,-0.004132,0.981818
6,(Bread),(Diapers),0.318182,0.363636,0.181818,0.571429,1.571429,0.066116,1.484848
7,(Diapers),(Bread),0.363636,0.318182,0.181818,0.500000,1.571429,0.066116,1.363636
8,(Milk),(Bread),0.590909,0.318182,0.181818,0.307692,0.967033,-0.006198,0.984848
9,(Bread),(Milk),0.318182,0.590909,0.181818,0.571429,0.967033,-0.006198,0.954545
10,(Diapers),(Cola),0.363636,0.590909,0.136364,0.375000,0.634615,-0.078512,0.654545
11,(Cola),(Diapers),0.590909,0.363636,0.136364,0.230769,0.634615,-0.078512,0.827273
12,(Milk),(Cola),0.590909,0.590909,0.363636,0.615385,1.041420,0.014463,1.063636
13,(Cola),(Milk),0.590909,0.590909,0.363636,0.615385,1.041420,0.014463,1.063636
14,(Milk),(Diapers),0.590909,0.363636,0.227273,0.384615,1.057692,0.012397,1.034091
15,(Diapers),(Milk),0.363636,0.590909,0.227273,0.625000,1.057692,0.012397,1.090909
16,"(Milk, Cola)",(Beer),0.363636,0.545455,0.136364,0.375000,0.687500,-0.061983,0.727273
17,"(Milk, Beer)",(Cola),0.318182,0.590909,0.136364,0.428571,0.725275,-0.051653,0.715909
18,"(Cola, Beer)",(Milk),0.272727,0.590909,0.136364,0.500000,0.846154,-0.024793,0.818182
19,(Milk),"(Cola, Beer)",0.590909,0.272727,0.136364,0.230769,0.846154,-0.024793,0.945455
20,(Cola),"(Milk, Beer)",0.590909,0.318182,0.136364,0.230769,0.725275,-0.051653,0.886364
21,(Beer),"(Milk, Cola)",0.545455,0.363636,0.136364,0.250000,0.687500,-0.061983,0.848485
22,"(Milk, Diapers)",(Cola),0.227273,0.590909,0.136364,0.600000,1.015385,0.002066,1.022727
23,"(Milk, Cola)",(Diapers),0.363636,0.363636,0.136364,0.375000,1.031250,0.004132,1.018182
24,"(Diapers, Cola)",(Milk),0.136364,0.590909,0.136364,1.000000,1.692308,0.055785,inf
25,(Milk),"(Diapers, Cola)",0.590909,0.136364,0.136364,0.230769,1.692308,0.055785,1.122727
26,(Diapers),"(Milk, Cola)",0.363636,0.363636,0.136364,0.375000,1.031250,0.004132,1.018182
27,(Cola),"(Milk, Diapers)",0.590909,0.227273,0.136364,0.230769,1.015385,0.002066,1.004545

**** Krithik's Bazaar *****
Here is what we sell
['Beer', 'Bread', 'Cola', 'Diapers', 'Eggs', 'Milk']
Do you want to Buy something?
Press 'y' for Yes and 'n' for No: y
enter your item here: Milk
Milk is added to the cart
 ['Milk']

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
4,(Milk),(Beer),0.590909,0.545455,0.318182,0.538462,0.987179,-0.004132,0.984848
8,(Milk),(Bread),0.590909,0.318182,0.181818,0.307692,0.967033,-0.006198,0.984848
12,(Milk),(Cola),0.590909,0.590909,0.363636,0.615385,1.041420,0.014463,1.063636
14,(Milk),(Diapers),0.590909,0.363636,0.227273,0.384615,1.057692,0.012397,1.034091
16,"(Milk, Cola)",(Beer),0.363636,0.545455,0.136364,0.375000,0.687500,-0.061983,0.727273
17,"(Milk, Beer)",(Cola),0.318182,0.590909,0.136364,0.428571,0.725275,-0.051653,0.715909
19,(Milk),"(Cola, Beer)",0.590909,0.272727,0.136364,0.230769,0.846154,-0.024793,0.945455
22,"(Milk, Diapers)",(Cola),0.227273,0.590909,0.136364,0.600000,1.015385,0.002066,1.022727
23,"(Milk, Cola)",(Diapers),0.363636,0.363636,0.136364,0.375000,1.031250,0.004132,1.018182
25,(Milk),"(Diapers, Cola)",0.590909,0.136364,0.136364,0.230769,1.692308,0.055785,1.122727

Do you want to Buy?
['Beer']
['Bread']
['Cola']
['Diapers']
['Beer']
['Cola']
['Cola', 'Beer']
['Cola']
['Diapers']
['Diapers', 'Cola']
Do you want to Buy something?
Press 'y' for Yes and 'n' for No: y
enter your item here: Cola
Cola is added to the cart
 ['Milk', 'Cola']

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
16,"(Milk, Cola)",(Beer),0.363636,0.545455,0.136364,0.375,0.68750,-0.061983,0.727273
23,"(Milk, Cola)",(Diapers),0.363636,0.363636,0.136364,0.375,1.03125,0.004132,1.018182

Do you want to Buy?
['Beer']
['Diapers']
Do you want to Buy something?
Press 'y' for Yes and 'n' for No: y
enter your item here: Beer
Beer is added to the cart
 ['Milk', 'Cola', 'Beer']

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, leverage, conviction]
Index: []

Do you want to Buy something?
Press 'y' for Yes and 'n' for No: n
Your purchases are: ['Milk', 'Cola', 'Beer']

In [10]:
# import pandas as pd
# from mlxtend.preprocessing import TransactionEncoder
# from mlxtend.frequent_patterns import apriori
# from mlxtend.frequent_patterns import association_rules
# f = open('demo.txt', 'r')
# ds = eval(f.read())
# f.close()
# te=TransactionEncoder()
# te=te.fit(ds)
# te_ary=te.transform(ds)
# df=pd.DataFrame(te_ary,columns=te.columns_)
# all_items=te.columns_
# ref=list(te.columns_)
# cart=[]
# frequent_itemsets=apriori(df,min_support=0.4,use_colnames=True)
# rules=association_rules(frequent_itemsets,metric="support",min_threshold=0.4)
# rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Milk),(Beer),0.727273,0.727273,0.545455,0.750000,1.031250,0.016529,1.090909
1,(Beer),(Milk),0.727273,0.727273,0.545455,0.750000,1.031250,0.016529,1.090909
2,(Milk),(Cola),0.727273,0.545455,0.454545,0.625000,1.145833,0.057851,1.212121
3,(Cola),(Milk),0.545455,0.727273,0.454545,0.833333,1.145833,0.057851,1.636364

In [3]:
# print(ds)
# fo=open('demo.txt','w')
# fo.write(repr(ds))

[['Bread', 'Milk', 'Beer'], ['Bread', 'Diapers', 'Eggs'], ['Milk', 'Diapers', 'Beer', 'Cola'], ['Bread', 'Milk', 'Diapers', 'Beer'], ['Bread', 'Milk', 'Cola'], ['Milk', 'Beer', 'Cola'], ['Milk', 'Cola', 'Diapers'], ['Milk', 'Beer'], ['Beer', 'Diapers'], ['Eggs', 'Beer', 'Cola'], ['Beer', 'Milk', 'Cola'], ['Bread', 'Cola'], ['Bread', 'Milk', 'Eggs', 'Diapers'], ['Milk', 'Cola'], ['Cola', 'Milk'], ['Beer'], ['Cola', 'Milk', 'Diapers']]

437

In [10]:
f = open('demo.txt', 'r')
l = eval(f.read())
f.close()
cart=['Milk','Bread']
l.append(cart)
fo=open('demo.txt','w')
fo.write(repr(l))
fo.close()